from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.home, name="home"),
    path('signup/', views.signUp, name="signup"),
    path('login/', views.logIn, name="login"),
    path('logout/', views.logOut, name="logout"),

    path('addTopic/', views.addTopic, name="addTopic"),
    path('editTopic/', views.editTopic, name="editTopic"),
    path('deleteTopic/', views.deleteTopic, name="deleteTopic"),

    # path('', views.home_in, name="home_in"),
    # path('guest', views.home_out, name="home_out"),
    # path('logout', views.log_out, name="log_out"),
    # path('contact_us', views.contact_us, name="contact_us"),
    # # path('event', views.event, name="event"),
    # path('user', views.user, name="user"),
    # path('rate/<int:project_id>', views.rate_project, name="project_rate"),
    # path('reply/<int:rating_id>', views.reply, name="reply"),
    # path('profile/<int:member>',views.profile, name="profile"),
    # path('remove_user/<int:profile_id>', views.remove_user, name="remove_user"),
    # path('definition/<int:profile_id>', views.definition, name="definition"),
    # path('edit_definition/<int:profile_id>', views.edit_definition, name="edit_definition"),
    # path('remove_definition/<int:profile_id>', views.remove_definition, name="remove_definition"),
    # path('description/<int:profile_id>', views.description, name="description"),
    # path('edit_description/<int:profile_id>', views.edit_description, name="edit_description"),
    # path('remove_description/<int:profile_id>', views.remove_description, name="remove_description"),

    # path('idea/', views.idea, name="idea"),
    # path('idea/add_idea', views.add_idea, name="add_idea"),
    # path('idea/search/', views.search, name="search"),
    # path('idea/status/<int:task_id>', views.status, name="change_status"),
    # path('idea/supplement/<int:idea_id>', views.supplement, name="supplement"),
    # path('idea/task/<int:idea_id>', views.task, name="task"),
    # path('idea/task_details/<int:task_id>', views.task_details, name="task_details"),
    # path('idea/rate/<int:idea_id>', views.rate, name="rate"),
    # path('idea/approve/<int:task_id>', views.approve, name="approve"),
    # path('idea/<int:idea_id>', views.idea_details, name="idea_details"),
    # path('idea/link/<int:task_id>', views.link, name="link"),
    # path('idea/idea_link/<int:idea_id>', views.idea_link, name="idea_link"),
    # path('idea/publish/<int:idea_id>', views.publish, name="publish"),
    # path('idea/reference/<int:task_id>', views.reference, name="reference"),
    # path('idea/milestones/<int:task_id>', views.milestones, name="milestones"),
    # path('idea/learning/<int:task_id>', views.learning, name="learning"),
    # path('idea/remove_reference/<int:reference_id>', views.remove_reference, name="remove_reference"),
    # path('idea/rate_resource/<int:resource_id>', views.rate_resource, name="rate_resource"),
    # path('idea/delete_resource/<int:resource_id>', views.delete_resource, name="delete_resource"),
    # path('idea/edit_supplement/<int:idea_id>', views.edit_supplement, name="edit_supplement"),
    # path('idea/delete_supplement/<int:idea_id>', views.delete_supplement, name="delete_supplement"),
    # path('idea/supplement_status/<int:idea_id>', views.supplement_status, name="supplement_status"),
    # path('idea/update_task/<int:idea_id>', views.update_task, name="update_task"),
    # path('idea/get_tasks/<int:idea_id>', views.get_tasks, name="get_tasks"),
    # path('idea/update_version/<int:idea_id>', views.update_version, name="update_version"),
    # path('idea/delete_task/<int:idea_id>', views.delete_task, name="delete_task"),
    # path('idea/edit_idea/<int:idea_id>', views.edit_idea, name="edit_idea"),
    # path('idea/delete_idea/<int:idea_id>', views.delete_idea, name="delete_idea"),
    # path('idea/edit_resource/<int:resource_id>', views.edit_resource, name="edit_resource"),
    # path('idea/search_resource/<int:task_id>', views.search_resource, name="search_resource"),
    # path('idea/milestone_status/<int:milestone_id>', views.milestone_status, name="milestone_status"),
    # path('idea/edit_milestone/<int:milestone_id>', views.edit_milestone, name="edit_milestone"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)