# Generated by Django 2.2.12 on 2021-12-20 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MergedSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.TextField(blank=True, null=True)),
                ('attachedMergedSummaries', models.ManyToManyField(blank=True, related_name='linkedMergedSummaries', to='research_app.MergedSummary')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('docType', models.CharField(max_length=50)),
                ('folders', models.ManyToManyField(blank=True, related_name='topics', to='research_app.Folder')),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchWorkDuplicate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('work', models.TextField(blank=True, null=True)),
                ('originalResearchWork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='researchWorkDuplicates', to='research_app.ResearchWork')),
                ('originalResearchWorkDuplicate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='researchWorkDuplicates', to='research_app.ResearchWorkDuplicate')),
            ],
        ),
        migrations.AddField(
            model_name='researchwork',
            name='topic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='researchWork', to='research_app.Topic'),
        ),
        migrations.CreateModel(
            name='ResearchSummaryDuplicate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('work', models.TextField(blank=True, null=True)),
                ('originalResearchSummary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='researchSummaryDuplicates', to='research_app.ResearchSummary')),
                ('originalResearchSummaryDuplicate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='researchSummaryDuplicates', to='research_app.ResearchSummaryDuplicate')),
            ],
        ),
        migrations.AddField(
            model_name='researchsummary',
            name='researchWork',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='researchSummary', to='research_app.ResearchWork'),
        ),
        migrations.CreateModel(
            name='MergedSummaryDuplicate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('work', models.TextField(blank=True, null=True)),
                ('attachedMergedSummary', models.ManyToManyField(blank=True, related_name='linkedMergedSummaryDuplicates', to='research_app.MergedSummary')),
                ('attachedResearchSummary', models.ManyToManyField(blank=True, related_name='linkedMergedSummaryDuplicates', to='research_app.ResearchSummary')),
                ('attachedResearchWorks', models.ManyToManyField(blank=True, related_name='linkedMergedSummaryDuplicates', to='research_app.ResearchWork')),
                ('originalMergedSummary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mergedSummaryDuplicates', to='research_app.MergedSummary')),
            ],
        ),
        migrations.AddField(
            model_name='mergedsummary',
            name='attachedResearchSummaries',
            field=models.ManyToManyField(blank=True, related_name='linkedMergedSummaries', to='research_app.ResearchSummary'),
        ),
        migrations.AddField(
            model_name='mergedsummary',
            name='attachedResearchWorks',
            field=models.ManyToManyField(blank=True, related_name='linkedMergedSummaries', to='research_app.ResearchWork'),
        ),
        migrations.AddField(
            model_name='mergedsummary',
            name='topic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='MergedSummary', to='research_app.Topic'),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.TextField()),
                ('researchWork', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='research_app.ResearchWork')),
                ('researchWorkDuplicate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='research_app.ResearchWorkDuplicate')),
            ],
        ),
        migrations.AddField(
            model_name='folder',
            name='topic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='folder', to='research_app.Topic'),
        ),
    ]
