# Generated by Django 2.2.12 on 2022-02-16 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('docType', models.CharField(default='Folder', max_length=50)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('LastModifiedAt', models.DateTimeField(auto_now=True)),
                ('parentFolder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='research_app.Folder')),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MergedSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('docType', models.CharField(default='Merged Summary', max_length=50)),
                ('work', models.TextField(default='')),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('LastModifiedAt', models.DateTimeField(auto_now=True)),
                ('attachedMergedSummaries', models.ManyToManyField(blank=True, related_name='linkedMergedSummaries', to='research_app.MergedSummary')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.TextField(default='')),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('LastModifiedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('docType', models.CharField(default='Research Work', max_length=50)),
                ('work', models.TextField(default='')),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('LastModifiedAt', models.DateTimeField(auto_now=True)),
                ('parentFolder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='researchWorks', to='research_app.Folder')),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='researchWorks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchWorkDuplicate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('work', models.TextField(default='')),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('LastModifiedAt', models.DateTimeField(auto_now=True)),
                ('originalResearchWork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='researchWorkDuplicates', to='research_app.ResearchWork')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchSummaryDuplicate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('work', models.TextField(default='')),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('LastModifiedAt', models.DateTimeField(auto_now=True)),
                ('originalResearchSummary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='researchSummaryDuplicates', to='research_app.ResearchSummary')),
            ],
        ),
        migrations.AddField(
            model_name='researchsummary',
            name='researchWork',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='researchSummary', to='research_app.ResearchWork'),
        ),
        migrations.CreateModel(
            name='MergedSummaryDuplicate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('work', models.TextField(default='')),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('LastModifiedAt', models.DateTimeField(auto_now=True)),
                ('originalMergedSummary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mergedSummaryDuplicates', to='research_app.MergedSummary')),
            ],
        ),
        migrations.AddField(
            model_name='mergedsummary',
            name='attachedMergedSummaryDuplicates',
            field=models.ManyToManyField(blank=True, related_name='linkedMergedSummaries', to='research_app.MergedSummaryDuplicate'),
        ),
        migrations.AddField(
            model_name='mergedsummary',
            name='attachedResearchSummaries',
            field=models.ManyToManyField(blank=True, related_name='linkedMergedSummaries', to='research_app.ResearchSummary'),
        ),
        migrations.AddField(
            model_name='mergedsummary',
            name='attachedResearchSummaryDuplicates',
            field=models.ManyToManyField(blank=True, related_name='linkedMergedSummaries', to='research_app.ResearchSummaryDuplicate'),
        ),
        migrations.AddField(
            model_name='mergedsummary',
            name='attachedResearchWorkDuplicates',
            field=models.ManyToManyField(blank=True, related_name='linkedMergedSummaries', to='research_app.ResearchWorkDuplicate'),
        ),
        migrations.AddField(
            model_name='mergedsummary',
            name='attachedResearchWorks',
            field=models.ManyToManyField(blank=True, related_name='linkedMergedSummaries', to='research_app.ResearchWork'),
        ),
        migrations.AddField(
            model_name='mergedsummary',
            name='parentFolder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mergedSummaries', to='research_app.Folder'),
        ),
        migrations.AddField(
            model_name='mergedsummary',
            name='researcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mergedSummaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.TextField()),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('LastModifiedAt', models.DateTimeField(auto_now=True)),
                ('researchWork', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='research_app.ResearchWork')),
                ('researchWorkDuplicate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='research_app.ResearchWorkDuplicate')),
            ],
        ),
    ]
