# Generated by Django 2.2.12 on 2022-02-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mergedsummaryduplicate',
            name='originalMergedSummary',
        ),
        migrations.RemoveField(
            model_name='researchsummary',
            name='researchWork',
        ),
        migrations.RemoveField(
            model_name='researchsummaryduplicate',
            name='originalResearchSummary',
        ),
        migrations.RemoveField(
            model_name='mergedsummary',
            name='attachedMergedSummaryDuplicates',
        ),
        migrations.RemoveField(
            model_name='mergedsummary',
            name='attachedResearchSummaries',
        ),
        migrations.RemoveField(
            model_name='mergedsummary',
            name='attachedResearchSummaryDuplicates',
        ),
        migrations.AddField(
            model_name='researchwork',
            name='summary',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='researchworkduplicate',
            name='summary',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.DeleteModel(
            name='MergedSummaryDuplicate',
        ),
        migrations.DeleteModel(
            name='ResearchSummary',
        ),
        migrations.DeleteModel(
            name='ResearchSummaryDuplicate',
        ),
    ]
