# Generated by Django 2.2.12 on 2021-12-19 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parentFolder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childFolders', to='research_app.Folder'),
        ),
        migrations.AlterField(
            model_name='link',
            name='researchWork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='research_app.ResearchWork'),
        ),
        migrations.AlterField(
            model_name='link',
            name='researchWorkDuplicate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='research_app.ResearchWorkDuplicate'),
        ),
        migrations.AlterField(
            model_name='mergedsummary',
            name='attachedMergedSummaries',
            field=models.ManyToManyField(blank=True, related_name='linkedMergedSummaries', to='research_app.MergedSummary'),
        ),
        migrations.AlterField(
            model_name='mergedsummary',
            name='attachedResearchSummaries',
            field=models.ManyToManyField(blank=True, related_name='linkedMergedSummaries', to='research_app.ResearchSummary'),
        ),
        migrations.AlterField(
            model_name='mergedsummary',
            name='attachedResearchWorks',
            field=models.ManyToManyField(blank=True, related_name='linkedMergedSummaries', to='research_app.ResearchWork'),
        ),
        migrations.AlterField(
            model_name='mergedsummary',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mergedsummary',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mergedSummaries', to='research_app.Folder'),
        ),
        migrations.AlterField(
            model_name='mergedsummary',
            name='work',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mergedsummaryduplicate',
            name='attachedMergedSummary',
            field=models.ManyToManyField(blank=True, related_name='linkedMergedSummaryDuplicates', to='research_app.MergedSummary'),
        ),
        migrations.AlterField(
            model_name='mergedsummaryduplicate',
            name='attachedResearchSummary',
            field=models.ManyToManyField(blank=True, related_name='linkedMergedSummaryDuplicates', to='research_app.ResearchSummary'),
        ),
        migrations.AlterField(
            model_name='mergedsummaryduplicate',
            name='attachedResearchWorks',
            field=models.ManyToManyField(blank=True, related_name='linkedMergedSummaryDuplicates', to='research_app.ResearchWork'),
        ),
        migrations.AlterField(
            model_name='mergedsummaryduplicate',
            name='work',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researchsummary',
            name='work',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researchsummaryduplicate',
            name='originalResearchSummaryDuplicate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='researchSummaryDuplicates', to='research_app.ResearchSummaryDuplicate'),
        ),
        migrations.AlterField(
            model_name='researchsummaryduplicate',
            name='work',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researchwork',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researchwork',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='researchWorks', to='research_app.Folder'),
        ),
        migrations.AlterField(
            model_name='researchwork',
            name='work',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researchworkduplicate',
            name='originalResearchWorkDuplicate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='researchWorkDuplicates', to='research_app.ResearchWorkDuplicate'),
        ),
        migrations.AlterField(
            model_name='researchworkduplicate',
            name='work',
            field=models.TextField(blank=True, null=True),
        ),
    ]
