# Generated by Django 2.2.12 on 2021-12-20 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='folders',
        ),
        migrations.AddField(
            model_name='topic',
            name='parentFolder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='research_app.Folder'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='topic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='research_app.Topic'),
        ),
        migrations.AlterField(
            model_name='mergedsummary',
            name='topic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='research_app.Topic'),
        ),
        migrations.AlterField(
            model_name='researchwork',
            name='topic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='research_app.Topic'),
        ),
    ]
