# Generated by Django 2.2.12 on 2021-12-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_app', '0002_auto_20211219_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='parentFolder',
        ),
        migrations.AddField(
            model_name='folder',
            name='parentFolders',
            field=models.ManyToManyField(blank=True, related_name='childFolders', to='research_app.Folder'),
        ),
        migrations.RemoveField(
            model_name='mergedsummary',
            name='folder',
        ),
        migrations.AddField(
            model_name='mergedsummary',
            name='folder',
            field=models.ManyToManyField(blank=True, related_name='mergedSummaries', to='research_app.Folder'),
        ),
        migrations.RemoveField(
            model_name='researchwork',
            name='folder',
        ),
        migrations.AddField(
            model_name='researchwork',
            name='folder',
            field=models.ManyToManyField(blank=True, related_name='researchWorks', to='research_app.Folder'),
        ),
    ]
