# Generated by Django 2.2.12 on 2021-12-22 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_app', '0002_auto_20211220_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mergedsummary',
            name='work',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='mergedsummaryduplicate',
            name='work',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='researchsummary',
            name='work',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='researchsummaryduplicate',
            name='work',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='researchwork',
            name='work',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='researchworkduplicate',
            name='work',
            field=models.TextField(default=''),
        ),
    ]
