# Generated by Django 2.2.12 on 2021-12-22 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_app', '0003_auto_20211222_0721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchsummaryduplicate',
            name='originalResearchSummaryDuplicate',
        ),
        migrations.RemoveField(
            model_name='researchworkduplicate',
            name='originalResearchWorkDuplicate',
        ),
    ]
