# Generated by Django 2.2.12 on 2021-12-23 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research_app', '0004_auto_20211222_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergedsummary',
            name='attachedMergedSummaryDuplicates',
            field=models.ManyToManyField(blank=True, related_name='linkedMergedSummaries', to='research_app.MergedSummaryDuplicate'),
        ),
        migrations.AddField(
            model_name='mergedsummary',
            name='attachedResearchSummaryDuplicates',
            field=models.ManyToManyField(blank=True, related_name='linkedMergedSummaries', to='research_app.ResearchSummaryDuplicate'),
        ),
        migrations.AddField(
            model_name='mergedsummary',
            name='attachedResearchWorkDuplicates',
            field=models.ManyToManyField(blank=True, related_name='linkedMergedSummaries', to='research_app.ResearchWorkDuplicate'),
        ),
        migrations.AddField(
            model_name='mergedsummaryduplicate',
            name='attachedMergedSummaryDuplicates',
            field=models.ManyToManyField(blank=True, related_name='linkedMergedSummaryDuplicates', to='research_app.MergedSummaryDuplicate'),
        ),
        migrations.AddField(
            model_name='mergedsummaryduplicate',
            name='attachedResearchSummaryDuplicates',
            field=models.ManyToManyField(blank=True, related_name='linkedMergedSummaryDuplicates', to='research_app.ResearchSummaryDuplicate'),
        ),
        migrations.AddField(
            model_name='mergedsummaryduplicate',
            name='attachedResearchWorkDuplicates',
            field=models.ManyToManyField(blank=True, related_name='linkedMergedSummaryDuplicates', to='research_app.ResearchWorkDuplicate'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='topic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='folder', to='research_app.Topic'),
        ),
        migrations.AlterField(
            model_name='mergedsummary',
            name='topic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='MergedSummary', to='research_app.Topic'),
        ),
        migrations.AlterField(
            model_name='researchwork',
            name='topic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ResearchWork', to='research_app.Topic'),
        ),
    ]
