# Generated by Django 2.2.12 on 2021-12-24 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_app', '0005_auto_20211223_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mergedsummaryduplicate',
            name='attachedMergedSummary',
        ),
        migrations.RemoveField(
            model_name='mergedsummaryduplicate',
            name='attachedMergedSummaryDuplicates',
        ),
        migrations.RemoveField(
            model_name='mergedsummaryduplicate',
            name='attachedResearchSummary',
        ),
        migrations.RemoveField(
            model_name='mergedsummaryduplicate',
            name='attachedResearchSummaryDuplicates',
        ),
        migrations.RemoveField(
            model_name='mergedsummaryduplicate',
            name='attachedResearchWorkDuplicates',
        ),
        migrations.RemoveField(
            model_name='mergedsummaryduplicate',
            name='attachedResearchWorks',
        ),
    ]
