# Generated by Django 2.2.12 on 2021-12-26 05:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('research_app', '0006_auto_20211224_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='CreatedAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='folder',
            name='LastModifiedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='link',
            name='CreatedAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='LastModifiedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mergedsummary',
            name='CreatedAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mergedsummary',
            name='LastModifiedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mergedsummaryduplicate',
            name='CreatedAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mergedsummaryduplicate',
            name='LastModifiedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='researchsummary',
            name='CreatedAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchsummary',
            name='LastModifiedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='researchsummaryduplicate',
            name='CreatedAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchsummaryduplicate',
            name='LastModifiedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='researchwork',
            name='CreatedAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchwork',
            name='LastModifiedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='researchworkduplicate',
            name='CreatedAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchworkduplicate',
            name='LastModifiedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='CreatedAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='LastModifiedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
